"""
This type stub file was generated by pyright.
"""

@<Expression>
class :
   ...


@<Expression>
class :
   ...


@<Expression>
class :
   ...


@<Expression>
@<Expression>
@<Expression>
class :
   ...


@<Expression>
@<Expression>
@<Expression>
@<Expression>
@<Expression>
class :
   ...


@<Expression>
class :
   ...


@<Expression>
class :
   ...


@<Expression>
class :
   ...


@<Expression>
class :
   ...


@<Expression>
class :
   ...


@<Expression>
class :
   ...


@<Expression>
class :
   ...


@<Expression>
class :
   ...


@<Expression>
class :
   ...


@<Expression>
class :
   ...


@<Expression>
class :
   ...


@<Expression>
class :
   ...


@<Expression>
class :
   ...


@<Expression>
@<Expression>
class :
   ...


@<Expression>
class :
   ...


@<Expression>
class :
   ...


@<Expression>
@<Expression>
class :
   ...


@<Expression>
class :
   ...


@<Expression>
class :
   ...


@<Expression>
class :
   ...


@<Expression>
class :
   ...


@<Expression>
@<Expression>
@<Expression>
class :
   ...


@<Expression>
class :
   ...


are: <Expression>
GDALMajorObjectShadow: <Expression>
GDALMajorObjectShadow: <Expression>
information: <Expression>
are: <Expression>
GDALTransformerInfoShadow: <Expression>
GDALTransformerInfoShadow: <Expression>
@<Expression>
class :
   ...


