"""
This type stub file was generated by pyright.
"""

@<Expression>
class :
  ...


@<Expression>
class :
  ...


@<Expression>
@<Expression>
@<Expression>
class :
  ...


@<Expression>
@<Expression>
@<Expression>
@<Expression>
@<Expression>
class :
  ...


@<Expression>
class :
  ...


@<Expression>
class :
  ...


L: p
Parameters: <Expression>
hDS: handle
NOTE: Starting
Parameters: <Expression>
hDS: handle
Parameters: <Expression>
hDS: handle
Parameters: <Expression>
hDS: handle
iLayer: the
GDALDataset: <Expression>
Parameters: <Expression>
hDS: The
pszName: the
hSpatialRef: handle
eType: the
papszOptions: a
name = ...
url: http
Example: <Expression>
Parameters: <Expression>
hDS: handle
hSrcLayer: handle
pszNewName: the
papszOptions: a
name = ...
Parameters: <Expression>
hDS: handle
pszLayerName: Layer
ODsCCreateLayer: <Expression>
ODsCDeleteLayer: <Expression>
ODsCCreateGeomFieldAfterCreateLayer: <Expression>
ODsCCurveGeometries: <Expression>
Parameters: <Expression>
hDS: handle
pszCapability: the
Parameters: <Expression>
hDS: handle
pszStatement: the
hSpatialFilter: handle
pszDialect: allows
Parameters: <Expression>
hDS: a
hLayer: handle
OGRLayer: <Expression>
Parameters: <Expression>
hLayer: handle
hGeom: handle
OGRLayer: <Expression>
OGRLayer: <Expression>
OGRLayer: <Expression>
Parameters: <Expression>
hLayer: handle
dfMinX: the
dfMinY: the
dfMaxX: the
dfMaxY: the
OGRLayer: <Expression>
Parameters: <Expression>
hLayer: handle
document: <Expression>
http: <Expression>
OGRLayer: <Expression>
Parameters: <Expression>
hLayer: handle
pszQuery: query in restricted
Parameters: <Expression>
hLayer: handle
Parameters: <Expression>
hLayer: handle
Parameters: <Expression>
hLayer: handle
OGRLayer: <Expression>
Parameters: <Expression>
hLayer: handle
Parameters: <Expression>
hLayer: handle
Parameters: <Expression>
hLayer: handle
nFeatureId: the
OGRLayer: <Expression>
Parameters: <Expression>
hLayer: handle
Parameters: <Expression>
hLayer: handle
nIndex: the
Parameters: <Expression>
hLayer: handle
hFeat: the
