"""
This type stub file was generated by pyright.
"""

@<Expression>
class :
   ...


@<Expression>
class :
   ...


@<Expression>
@<Expression>
@<Expression>
class :
   ...


@<Expression>
@<Expression>
@<Expression>
@<Expression>
@<Expression>
class :
   ...


@<Expression>
class :
   ...


@<Expression>
class :
   ...


@<Expression>
class :
   ...


@<Expression>
class :
   ...


@<Expression>
class :
   ...


@<Expression>
class :
   ...


@<Expression>
class :
   ...


@<Expression>
class :
   ...


@<Expression>
class :
   ...


@<Expression>
class :
   ...


@<Expression>
class :
   ...


@<Expression>
@<Expression>
class :
   ...


@<Expression>
class :
   ...


@<Expression>
class :
   ...


@<Expression>
class :
   ...


@<Expression>
@<Expression>
@<Expression>
@<Expression>
class :
   ...


@<Expression>
class :
   ...


are: <Expression>
OSRCoordinateTransformationShadow: <Expression>
OSRCoordinateTransformationShadow: <Expression>
information: <Expression>
are: <Expression>
OSRCoordinateTransformationShadow: <Expression>
OSRCoordinateTransformationShadow: <Expression>
OSRCoordinateTransformationShadow: <Expression>
OSRCoordinateTransformationShadow: <Expression>
